[package]
name = "breakout"
version = "0.1.0"
authors = ["Allora"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
float-cmp = "0.6.0"

[dependencies.amethyst]
version = "0.14.0"
features = ["vulkan", "no-slow-safety-checks"]